IdentityAccessManager/urls.py
"""
Definition of urls for IdentityAccessManager.
"""

from datetime import datetime
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static

from app import urls
from restapi import urls as rurls

urlpatterns = patterns('',
    url(r'^',                   include(urls.endpoints)),
    url(r'^',                   include(urls.private_api,   namespace="private_api")),
    url(r'^api/',               include(rurls.endpoints,    namespace='public_api')),
    url(r'^docs/',              include('rest_framework_swagger.urls', namespace="docs")), 
    url(r'^api-auth/',          include('rest_framework.urls',  namespace='rest_framework')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# change the http.conf from /static -> /prosperity4all/identity-access-manager/static
#urlpatterns = patterns('',
#    url(r'^prosperity4all/identity-access-manager/',                   include(urls.endpoints)),
#    url(r'^prosperity4all/identity-access-manager/',                   include(urls.private_api,   namespace="private_api")),
#    url(r'^prosperity4all/identity-access-manager/api/',               include(rurls.endpoints,    namespace='public_api')),
#    url(r'^prosperity4all/identity-access-manager/docs/',              include('rest_framework_swagger.urls', namespace="docs")), 
#    url(r'^prosperity4all/identity-access-manager/api-auth/',          include('rest_framework.urls',  namespace='rest_framework')),
#) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.conf.urls import patterns, url, include
from app.views import *


# Endpoints for views
endpoints = patterns(
    '',
    url(r'^signup-request/$',                                           EmailForm.as_view(),                                    name='signup_request_form'), 
    url(r'^signup/$',                                                   RegistrationView.as_view(),                             name='signup_form'), 
    url(r'^login/$',                                                    LoginView.as_view(),                                    name='login_form'), 
    url(r'^index/$',                                                    DashboardView.as_view(),                                name='dashboard_form'), 
    url(r'^profile/$',                                                  ProfileView.as_view(),                                  name='profile_preview'), 
    url(r'^profile/change-password/$',                                  ProfileChangePwdView.as_view(),                         name='profile_change_pwd'), 
    url(r'^profile/edit/$',                                             ProfileUpdateView.as_view(),                            name='profile_update'), 
    url(r'^applications/$',                                             ApplicationListView.as_view(),                          name='applications_form'), 
    url(r'^applications/register/$',                                    ApplicationCreateView.as_view(),                        name='application_form'), 
    url(r'^applications/(?P<clientId>[0-9a-zA-Z-]+)/$',                 ApplicationPreView.as_view(),                           name='application_info_form'), 
    url(r'^applications/(?P<clientId>[0-9a-zA-Z-]+)/edit/$',            ApplicationUpdateView.as_view(),                        name='application_edit_form'), 
    url(r'^applications/(?P<clientId>[0-9a-zA-Z-]+)/roles/$',           ApplicationRolesView.as_view(),                         name='application_role_form'), 
    url(r'^applications/(?P<clientId>[0-9a-zA-Z-]+)/members/$',         ApplicationAuthMembersView.as_view(),                   name='application_auth_members_form'), 
    url(r'^authorized-applications/overview/$',                         ApplicationsListView.as_view(),                         name='list_applications_form'), 
    url(r'^authorized-applications/(?P<clientId>[0-9a-zA-Z-]+)/roles/$',AuthorizedApplicationRolesView.as_view(),               name='authorized_application_role_form'), 
    url(r'^authorized-applications/access/$',                           AuthorizedApplicationsView.as_view(),                   name='authorized_applications_form'), 
    url(r'^oauth2/authorize/$',                                         AuthorizeApplicationView.as_view(),                     name='authorize_app_form'),

)

# Private API
private_api = patterns(
    '',
    url(r'^iam/openam/authenticate$',                                   MemberAuthentication.as_view({"post": "create"}),                       name='authenticate_url'), 
    url(r'^iam/openam/prepare/register$',                               PrepareRegistration.as_view({'post': 'create'}),                        name='pre_registration_url'), 
    url(r'^iam/openam/users$',                                          MembersListAPIView.as_view({'post': 'create', "get": "retrieve"}),      name='users_url'),
    url(r'^iam/openam/users/(?P<username>[a-zA-Z0-9]+)$',               Members.as_view({"put": 'update'}),                                     name='user_url'),
    url(r'^iam/openam/users/(?P<username>[a-zA-Z0-9]+)/logo$',          UploadUserLogo.as_view(),                                               name="user_logo"), 
    url(r'^iam/openam/users/(?P<username>[a-zA-Z0-9]+)/password$',      MemberChangePasswordAPIView.as_view({"put": 'update'}),                 name='change_password_url'),
    url(r'^iam/openam/requests$',                                       Requests.as_view({"get": "retrieve"}),                                  name='requests_url'),
    url(r'^iam/openam/logout$',                                         Logout.as_view({"get": "retrieve"}),                                    name='logout_url'), 
    url(r'^iam/openam/authorize$',                                      ClientAuthorization.as_view({"get": "retrieve"}),                       name='authorize_url'), 
    url(r'^iam/openam/roles$',                                          GenericRolesListAPIView.as_view({"post": "create", "get": "retrieve"}), name='add_role_url'), 
    url(r'^iam/openam/applications$',                                   ClientsList.as_view({"post": "create", "get": "retrieve"}),             name='application_url'), 
    url(r'^iam/openam/applications/(?P<clientId>[0-9a-zA-Z-]+)$',       ApplicationAPIView.as_view({"put":"update", "delete": "destroy"}),      name='update_application_url'), 
    url(r'^iam/openam/applications/(?P<clientId>[0-9a-zA-Z-]+)/roles$', ApplicationRolesAPIView.as_view({"put":"update"}),                      name='set_application_role_url'), 
    url(r'^iam/openam/authorized-applications/(?P<clientId>[0-9a-zA-Z-]+)/users/(?P<username>[a-zA-Z0-9]+)$',      ApplicationMemberAPIView.as_view({"post":"create", "delete": "destroy"}),   name='set_application_member_url'), 
    url(r'^iam/openam/authorized-applications/(?P<clientId>[0-9a-zA-Z-]+)/users/(?P<username>[a-zA-Z0-9]+)/roles$',ApplicationMemberHasRoleAPIView.as_view({"put":"update"}),                  name='set_member_application_roles_url'), 
    url(r'^iam/openam/authorized-applications/tokens$',                 ActiveAccessTokenListAPIView.as_view({"get": "retrieve"}),              name='access_tokens_url'), 
    url(r'^iam/openam/authorized-applications/tokens/(?P<id>[0-9a-zA-Z-]+)$',ActiveAccessTokenAPIView.as_view({"delete": "destroy"}),           name='access_token_url'), 
    url(r'^iam/oauth2/authorize$',                                      DirectClientAuthorization.as_view({"post": "create"}),                  name='authorize_direct_app_url'),


    # endpoints
    url(r'^roles$',        RolesList.as_view(),                                    name='roles_url'), 
    url(r'^users/(?P<username>[a-zA-Z0-9]+)/applications$',        MyApplicationsList.as_view(),                           name='my_applications_url'), 
)

app/templates/app/dashboard/application-registration.html
{% extends "app/base.html" %}

{% block navbar %}
    {% include "app/dashboard/top-menu.html" %}
{% endblock navbar %}

{% load staticfiles %}

{% block content %}
<div class="container body-content" id="main">

    {% block breadcrumb %}
    <ol class="breadcrumb" aria-label="breadcrumb">
        <li>
            <a href="{% url 'dashboard_form' %}" class="custom-inactive-breadcrumb" title="Home page">
                <span class="fa fa-home"></span> Home
            </a>
        </li>
        <li>
            <a href="{% url 'applications_form' %}" class="custom-inactive-breadcrumb" title="My applications">My applications</a>
        </li>
        {% if application == None %}
        <li class="active"> Register application</li>
        {% else %}
        <li>
            <a href="{% url 'application_info_form' clientId=clientId %}" class="custom-inactive-breadcrumb" title="{{ application.name }}">{{ application.name }}</a>
        </li>
        <li class="active"> Edit</li>
        {% endif %}
    </ol>
    {% endblock breadcrumb %}

    <div class="row">
        <div class="col-sm-12 col-lg-12 col-xs-12">
            <section name="registrationArea" role="region">

                {% if application %}
                <form action="{% url 'private_api:update_application_url' clientId=clientId %}" class="form-horizontal iam-form" method="put" id="updateAppForm" name="updateAppForm" role="form">
                {% else %}
                <form action="{% url 'private_api:application_url' %}" class="form-horizontal iam-form" method="post" id="registrationAppForm" name="registrationAppForm" role="form">
                {% endif %}
                    <h3 class="" role="heading">
                        <span class="padding-left-20">{{title}}</span>
                        {% if application %}<span class="text-muted"> | <small><a href="{% url 'private_api:update_application_url' clientId=clientId %}" class="text-danger" id="remove-app"><span class="fa fa-trash-o" ></span> Delete </a> </small></span>{% endif %}
                    </h3>
                    <hr>
                    <fieldset>
                        <div class="form-group">
                            <div class="col-sm-4 col-md-4 col-lg-4 col-xs-12">
                                <label class="padding-left-20 control-label" for="name">Name <span style="color:red">*</span></label>
                            </div>
                            <div class="col-md-7 col-sm-7 col-lg-7 col-xs-12 controls" title="Type the application's name">
                                <input type="text" class="form-control" name="name" id="name" value="{{ application.name|default_if_none:"" }}" autocomplete="off" maxlength="200" placeholder="" autofocus required/>    
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-4 col-md-4 col-lg-4 col-xs-12">
                                <label class="padding-left-20 control-label" for="description">Description <span style="color:red">*</span></label>
                            </div>
                            <div class="col-md-7 col-sm-7 col-lg-7 col-xs-12 controls" title="Describe your application">
                                <textarea class="form-control" rows="6" name="description" id="description" autocomplete="off" maxlength="200" placeholder="" required>{{ application.description|default_if_none:"" }}</textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-4 col-md-4 col-lg-4 col-xs-12">
                                <label class="padding-left-20 control-label" for="url">URL <span style="color:red">*</span></label>
                            </div>
                            <div class="col-md-7 col-sm-7 col-lg-7 col-xs-12">
                                <input type="url" class="form-control" name="url" id="url" value="{{ application.url|default_if_none:"" }}" autocomplete="off" maxlength="100" placeholder="" required/>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-4 col-md-4 col-lg-4 col-xs-12">
                                <label class="padding-left-20 control-label" for="callback_url">Callback URL <span style="color:red">*</span></label>
                            </div>
                            <div class="col-md-7 col-sm-7 col-lg-7 col-xs-12">
                                <input type="url" class="form-control" name="callback_url" id="callback_url" value="{{ application.callback_url|default_if_none:"" }}" autocomplete="off" maxlength="200" placeholder="" required/>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-4 col-md-4 col-lg-4 col-xs-12">
                                <label class="padding-left-20 control-label" for="callback_url2">Callback URL 2</label>
                            </div>
                            <div class="col-md-7 col-sm-7 col-lg-7 col-xs-12">
                                <input type="url" class="form-control" name="callback_url2" id="callback_url2" value="{{ application.callback_url2|default_if_none:"" }}" autocomplete="off" maxlength="200" placeholder="" />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-4 col-md-4 col-lg-4 col-xs-12">
                                <label class="padding-left-20 control-label" for="mail">Email <span style="color:red">*</span></label>
                            </div>
                            <div class="col-md-7 col-sm-7 col-lg-7 col-xs-12 controls" title="Enter the contact info">
                                <input type="email" class="form-control" name="mail" id="mail" value="{{ mail|default_if_none:"" }}"  autocomplete="off" maxlength="200" placeholder="" />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-4 col-md-4 col-lg-4 col-xs-12"></div>
                            <div class="col-md-7 col-sm-7 col-lg-7 col-xs-12">
                                {% if application %}
                                <button type="submit" class="btn btn-primary btn-md" id="update-app-submit" role="button">Submit</button>
                                {% else %}
                                <button type="submit" class="btn btn-primary btn-md" id="register-app-submit" role="button">Submit</button>
                                {% endif %}
                                <button type="reset" class="btn btn-warning btn-md" id="register-app-reset" role="button">Reset</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </section>
        </div>
    </div>
</div>
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="{% static 'app/scripts/iam.js' %}"></script>
<script type="text/javascript" src="{% static 'app/scripts/cookies.js' %}"></script>
{% if application %}
<script type="text/javascript">
    $(document).ready(function () { 
        IAM.updateApplication("{% url 'application_info_form' clientId=clientId %}"); 
    }).on('click', '#remove-app', function(event) {
        event.preventDefault();
        IAM.deleteApplication($(this).attr('href'), "{% url 'applications_form' %}"); 
    });
</script>
{% else %}
<script type="text/javascript">$(document).ready(function () { IAM.registerApplication("{% url 'applications_form' %}"); });</script>
{% endif %}
{% endblock %}

app/templates/app/dashboard/application-roles.html
{% extends "app/base.html" %}

{% block navbar %}
    {% include "app/dashboard/top-menu.html" %}
{% endblock navbar %}

{% load staticfiles %}

{% block content %}
<div class="container body-content " id="main">

    {% block breadcrumb %}
    <ol class="breadcrumb" aria-label="breadcrumb">
        <li>
            <a href="{% url 'dashboard_form' %}" class="custom-inactive-breadcrumb" title="Home page">
                <span class="fa fa-home"></span> Home
            </a>
        </li>
        <li>
            <a href="{% url 'applications_form' %}" class="custom-inactive-breadcrumb" title="My applications">My applications</a>
        </li>
        <li>
            <a href="{% url 'application_info_form' clientId=app.client_id %}" class="custom-inactive-breadcrumb" title="{{ app.name }}">{{ app.name }}</a>
        </li>
        <li class="active"> Manage roles</li>
    </ol>
    {% endblock breadcrumb %}
    <div>
        <div class="class="row col-sm-12 col-md-12 col-lg-12 col-xs-12" >
            <section name="setRolesArea" role="region">
                <form action="{% url 'private_api:set_application_role_url' clientId=app.client_id %}" class="form-horizontal iam-form" method="put" id="setRolesForm" name="setRolesForm" role="form">
                    <h3 class="padding-left-20" role="heading">
                        {{title}} in {{ app.name}}
                    </h3>
                    <hr>
                    <fieldset>
                        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                            <div class="col-md-4 col-lg-4 col-sm-4 col-xs-12 clearfix">
                                <div class="margin-bottom-25 panel panel-default">
                                  <div class="panel-body">
                                    <h4><span class="fa fa-book"></span> Instructions</h4>
                                  </div>
                                  <div class="panel-footer">
                                    <p class="text-justify">Please select the roles of the users that the {{app.name}} supports from the list and click on Save button. In case that this application does not support any role, ignore them.</p></div>
                                </div>
                            </div>
                            <div class="col-md-8 col-lg-8 col-sm-8 col-xs-12">
                                <div class="clearfix">
                                    <span class="pull-left">List of roles</span> 
                                    <a href="#addrole" id="add-role" class="pull-right"><span class="fa fa-plus text-primary"></span> Add</a>
                                </div>

                                <div class="list-group">
                                    {% if roles %}
                                        {% for i in roles %}
                                            {% if i.id in appRoles %}
                                            <a class="list-group-item cursor-pointer active" style="border-color: white !important"> 
                                                <h4 class="list-group-item-heading"><input type="checkbox" form="setRolesForm" name="{{ i.id }}" class="roles" id="role_{{ i.id }}" checked /> {{ i.type }}</h4>
                                                <p class="list-group-item-text">{{ i.description }}</p>
                                            </a>
                                            {% else %}
                                            <a class="list-group-item cursor-pointer">
                                                <h4 class="list-group-item-heading"><input type="checkbox" class="roles" name="{{ i.id }}" form="setRolesForm" id="role_{{ i.id }}"/> {{ i.type }}</h4>
                                                <p class="list-group-item-text">{{ i.description }}</p>
                                            </a>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="margin-bottom-25">
                                <button type="submit" class="btn btn-primary btn-md" id="set-roles-submit" role="button">Save</button>
                                <button type="reset" class="btn btn-warning btn-md" id="set-roles-reset" role="button">Reset</button>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </section>
        </div>
    </div>
</div>
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="{% static 'app/scripts/iam.js' %}"></script>
<script type="text/javascript" src="{% static 'app/scripts/cookies.js' %}"></script>
<script type="text/javascript" src="{% static 'app/scripts/bootbox/bootbox.min.js' %}"></script>
<script type="text/javascript">$(document).ready(function () { IAM.setApplicationRoles("{% url 'private_api:add_role_url' %}") });</script>
{% endblock %}

app/templates/app/dashboard/authorized-applications-member-has-role.html
{% extends "app/base.html" %}

{% block navbar %}
    {% include "app/dashboard/top-menu.html" %}
{% endblock navbar %}

{% load staticfiles %}

{% block content %}
<div class="container body-content " id="main">

    {% block breadcrumb %}
    <ol class="breadcrumb" aria-label="breadcrumb">
        <li>
            <a href="{% url 'dashboard_form' %}" class="custom-inactive-breadcrumb" title="Home page">
                <span class="fa fa-home"></span> Home
            </a>
        </li>
        <li>
            <a href="{% url 'list_applications_form' %}" class="custom-inactive-breadcrumb" title="Authorized applications">Authorized applications</a>
        </li>
        <li>
            <a href="{% url 'authorized_application_role_form' clientId=application.client_id %}" class="custom-inactive-breadcrumb" title="{{ application.name }}">{{ application.name }}</a>
        </li>
        <li class="active"> Declare roles</li>
    </ol>
    {% endblock breadcrumb %}
    <div>
        <div class="class="row col-sm-12 col-md-12 col-lg-12 col-xs-12" >
            <section name="memberRolesArea" role="region">
                <div class="iam-form clearfix">
                <!--form action="{% url 'private_api:set_member_application_roles_url' clientId=application.client_id  username=username%}" class="form-horizontal iam-form" method="put" id="memberRolesForm" name="memberRolesForm" role="form"-->
                    <h3 class="" role="heading">
                        <span class="padding-left-20">{{title}}</span>
                    </h3>
                    <hr>
                    <fieldset>
                        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                            <div class="col-md-4 col-lg-4 col-sm-4 col-xs-12 clearfix">
                                <div class="margin-bottom-25 panel panel-default">
                                  <div class="panel-body">
                                    <h4><span class="fa fa-book"></span> Instructions</h4>
                                  </div>
                                  <div class="panel-footer">
                                    <p class="text-justify">The application "{{application.name}}" supports the roles which are depicted in the list for its members. Please define what you want to do on this application by checking the relevant boxes.</p></div>
                                </div>
                            </div>

                            <div class="col-md-8 col-lg-8 col-sm-8 col-xs-12">
                                <form action="{% url 'private_api:set_application_member_url' clientId=application.client_id username=username %}" method="post" id="addMemberForm" name="addMemberForm">
                                    {% if applicationMember.id %}
                                    <h4 class="text-primary">You have already joined in the {{application.name}}. Do you want to remove from this membership?</h4>
                                    <div class="form-group well">
                                        <fieldset class="clearfix">
                                            <label class="text-muted hidden" style="margin-right: 20px"><input type="radio" name="member" value="1" readonly disabled/> YES (already joined)</label>
                                            <label class="cursor-pointer"><input type="radio" name='member' value="0" />  YES</label>
                                        </fieldset>
                                    </div>
                                    {% else %}
                                    <h4 class="text-primary">Do you want to join in the {{application.name}} membership?</h4>
                                    <div class="form-group well">
                                        <fieldset class="clearfix">
                                            <label class="cursor-pointer" style="margin-right: 20px"><input type="radio" name="member" value="1"/> YES</label>
                                            <label class="cursor-pointer"><input type="radio" name='member' value="0" />  NO</label>
                                        </fieldset>
                                    </div>
                                    {% endif %}

                                    <div class="clearfix">
                                        <label style="font-weight:normal !important">I agree with the <a href="#" id="use_member_agreement">Terms of usage</a></label>: 
                                        {% if applicationMember %}
                                        <input type="checkbox" id="terms_member" name="terms_member" checked/>
                                        {% else %}
                                        <input type="checkbox" id="terms_member" name="terms_member"/>
                                        {% endif %}
                                    </div>
                                    <div class="margin-bottom-10">
                                        <button type="submit" class="btn btn-primary btn-md" id="add-member-application" form="addMemberForm" role="button" >Submit</button>
                                        <button type="reset" class="btn btn-warning btn-md" id="clear-member-application" form="addMemberForm" role="button" >Reset</button>
                                    </div>
                                </form>

                                <hr />

                                {% if applicationMember.id %}
                                    <form action="{% url 'private_api:set_member_application_roles_url' clientId=application.client_id  username=username%}" class="form-horizontal" method="put" id="memberRolesForm" name="memberRolesForm" role="form">
                                        <h4 class="">List of available roles in {{application.name}}</h4>
                                        <div  class="list-group">
                                        {% if applicationRoles %}
                                            {% for i in applicationRoles %}
                                                {% if i.id in memberHasRoles %}
                                                <a class="list-group-item cursor-pointer active">
                                                    <h4 class="list-group-item-heading"><input type="checkbox" class="roles" checked name="{{ i.id }}" value="{{ i.id }}" form="memberRolesForm" id="app_role_{{ i.id }}"/> {{ i.role.type }}</h4>
                                                    <p class="list-group-item-text">{{ i.role.description }}</p>
                                                </a>
                                                {% else %}
                                                <a class="list-group-item cursor-pointer">
                                                    <h4 class="list-group-item-heading"><input type="checkbox" class="roles" name="{{ i.id }}" value="{{ i.id }}" form="memberRolesForm" id="app_role_{{ i.id }}"/> {{ i.role.type }}</h4>
                                                    <p class="list-group-item-text">{{ i.role.description }}</p>
                                                </a>
                                                {% endif %}
                                            {% endfor %}
                                        {% else %}
                                            <div class="well well-lg">No available roles for the <b>{{application.name}}</b>. Please contact with the administrator of the application.</div>
                                        {% endif %}
                                        </div>
                                        <div class="clearfix" style="margin: 0px">
                                            <label style="font-weight:normal !important">I agree with the <a href="#" id="use_agreement">Terms of usage</a></label>: 
                                            {% if memberHasRoles|length > 0 %}
                                            <input type="checkbox" id="terms_usage" name="terms_usage" checked/>
                                            {% else %}
                                            <input type="checkbox" id="terms_usage" name="terms_usage"/>
                                            {% endif %}
                                        </div>
                                        <input type="hidden" id="application_member" name="application_member" value="{{applicationMember.id}}"/>
                                        <div class="margin-bottom-10">
                                            <button type="submit" class="btn btn-primary btn-md" id="submit-member-roles" role="button">Save</button>
                                            <button type="reset" class="btn btn-warning btn-md" id="reset-member-roles" role="button">Reset</button>
                                        </div>
                                    </form>
                                {% endif %}

                             </div>
                        </div>
                    </fieldset>
                <!--form-->
                </div>

            </section>
        </div>
    </div>
</div>
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="{% static 'app/scripts/iam.js' %}"></script>
<script type="text/javascript" src="{% static 'app/scripts/cookies.js' %}"></script>
<script type="text/javascript">$(document).ready(function () { IAM.setApplicationMembership("{{application.name}}"); IAM.setMemberApplicationRoles("{{application.name}}"); });</script>
{% endblock %}