IdentityAccessManager/urls.py
"""
Definition of urls for IdentityAccessManager.
"""

from datetime import datetime
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static

from app import urls
from restapi import urls as rurls

urlpatterns = patterns('',
    url(r'^',                   include(urls.endpoints)),
    url(r'^',                   include(urls.private_api,   namespace="private_api")),
    url(r'^api/',               include(rurls.endpoints,    namespace='public_api')),
    url(r'^docs/',              include('rest_framework_swagger.urls', namespace="docs")), 
    url(r'^api-auth/',          include('rest_framework.urls',  namespace='rest_framework')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# change the http.conf from /static -> /prosperity4all/identity-access-manager/static
#urlpatterns = patterns('',
#    url(r'^prosperity4all/identity-access-manager/',                   include(urls.endpoints)),
#    url(r'^prosperity4all/identity-access-manager/',                   include(urls.private_api,   namespace="private_api")),
#    url(r'^prosperity4all/identity-access-manager/api/',               include(rurls.endpoints,    namespace='public_api')),
#    url(r'^prosperity4all/identity-access-manager/docs/',              include('rest_framework_swagger.urls', namespace="docs")), 
#    url(r'^prosperity4all/identity-access-manager/api-auth/',          include('rest_framework.urls',  namespace='rest_framework')),
#) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.conf.urls import patterns, url, include
from app.views import *


# Endpoints for views
endpoints = patterns(
    '',
    url(r'^signup-request/$',                                           EmailForm.as_view(),                                    name='signup_request_form'), 
    url(r'^signup/$',                                                   RegistrationView.as_view(),                             name='signup_form'), 
    url(r'^login/$',                                                    LoginView.as_view(),                                    name='login_form'), 
    url(r'^index/$',                                                    DashboardView.as_view(),                                name='dashboard_form'), 
    url(r'^profile/$',                                                  ProfileView.as_view(),                                  name='profile_preview'), 
    url(r'^profile/change-password/$',                                  ProfileChangePwdView.as_view(),                         name='profile_change_pwd'), 
    url(r'^profile/edit/$',                                             ProfileUpdateView.as_view(),                            name='profile_update'), 
    url(r'^applications/$',                                             ApplicationListView.as_view(),                          name='applications_form'), 
    url(r'^applications/register/$',                                    ApplicationCreateView.as_view(),                        name='application_form'), 
    url(r'^applications/(?P<clientId>[0-9a-zA-Z-]+)/$',                 ApplicationPreView.as_view(),                           name='application_info_form'), 
    url(r'^applications/(?P<clientId>[0-9a-zA-Z-]+)/edit/$',            ApplicationUpdateView.as_view(),                        name='application_edit_form'), 
    url(r'^applications/(?P<clientId>[0-9a-zA-Z-]+)/roles/$',           ApplicationRolesView.as_view(),                         name='application_role_form'), 
    url(r'^applications/(?P<clientId>[0-9a-zA-Z-]+)/members/$',         ApplicationAuthMembersView.as_view(),                   name='application_auth_members_form'), 
    url(r'^authorized-applications/overview/$',                         ApplicationsListView.as_view(),                         name='list_applications_form'), 
    url(r'^authorized-applications/(?P<clientId>[0-9a-zA-Z-]+)/roles/$',AuthorizedApplicationRolesView.as_view(),               name='authorized_application_role_form'), 
    url(r'^authorized-applications/access/$',                           AuthorizedApplicationsView.as_view(),                   name='authorized_applications_form'), 
    url(r'^oauth2/authorize/$',                                         AuthorizeApplicationView.as_view(),                     name='authorize_app_form'),

)

# Private API
private_api = patterns(
    '',
    url(r'^iam/openam/authenticate$',                                   MemberAuthentication.as_view({"post": "create"}),                       name='authenticate_url'), 
    url(r'^iam/openam/prepare/register$',                               PrepareRegistration.as_view({'post': 'create'}),                        name='pre_registration_url'), 
    url(r'^iam/openam/users$',                                          MembersListAPIView.as_view({'post': 'create', "get": "retrieve"}),      name='users_url'),
    url(r'^iam/openam/users/(?P<username>[a-zA-Z0-9]+)$',               Members.as_view({"put": 'update'}),                                     name='user_url'),
    url(r'^iam/openam/users/(?P<username>[a-zA-Z0-9]+)/logo$',          UploadUserLogo.as_view(),                                               name="user_logo"), 
    url(r'^iam/openam/users/(?P<username>[a-zA-Z0-9]+)/password$',      MemberChangePasswordAPIView.as_view({"put": 'update'}),                 name='change_password_url'),
    url(r'^iam/openam/requests$',                                       Requests.as_view({"get": "retrieve"}),                                  name='requests_url'),
    url(r'^iam/openam/logout$',                                         Logout.as_view({"get": "retrieve"}),                                    name='logout_url'), 
    url(r'^iam/openam/authorize$',                                      ClientAuthorization.as_view({"get": "retrieve"}),                       name='authorize_url'), 
    url(r'^iam/openam/roles$',                                          GenericRolesListAPIView.as_view({"post": "create", "get": "retrieve"}), name='add_role_url'), 
    url(r'^iam/openam/applications$',                                   ClientsList.as_view({"post": "create", "get": "retrieve"}),             name='application_url'), 
    url(r'^iam/openam/applications/(?P<clientId>[0-9a-zA-Z-]+)$',       ApplicationAPIView.as_view({"put":"update", "delete": "destroy"}),      name='update_application_url'), 
    url(r'^iam/openam/applications/(?P<clientId>[0-9a-zA-Z-]+)/roles$', ApplicationRolesAPIView.as_view({"put":"update"}),                      name='set_application_role_url'), 
    url(r'^iam/openam/authorized-applications/(?P<clientId>[0-9a-zA-Z-]+)/users/(?P<username>[a-zA-Z0-9]+)$',      ApplicationMemberAPIView.as_view({"post":"create", "delete": "destroy"}),   name='set_application_member_url'), 
    url(r'^iam/openam/authorized-applications/(?P<clientId>[0-9a-zA-Z-]+)/users/(?P<username>[a-zA-Z0-9]+)/roles$',ApplicationMemberHasRoleAPIView.as_view({"put":"update"}),                  name='set_member_application_roles_url'), 
    url(r'^iam/openam/authorized-applications/tokens$',                 ActiveAccessTokenListAPIView.as_view({"get": "retrieve"}),              name='access_tokens_url'), 
    url(r'^iam/openam/authorized-applications/tokens/(?P<id>[0-9a-zA-Z-]+)$',ActiveAccessTokenAPIView.as_view({"delete": "destroy"}),           name='access_token_url'), 
    url(r'^iam/oauth2/authorize$',                                      DirectClientAuthorization.as_view({"post": "create"}),                  name='authorize_direct_app_url'),


    # endpoints
    url(r'^roles$',        RolesList.as_view(),                                    name='roles_url'), 
    url(r'^users/(?P<username>[a-zA-Z0-9]+)/applications$',        MyApplicationsList.as_view(),                           name='my_applications_url'), 
)

app/templates/app/authorization.html
{% extends "app/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container body-content" id="main">
    <div class="row">
        <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
            <div class="well well-lg iam-form" style="min-height: 48%;">
                <h2>Identity and Access Management</h2>
                <hr>
                {% if app %}
                    <span>Enter your credentials to log in the <strong class=text-primary>{{ app.name }}</strong>.</span>
                    <br/>
                    {{ app.description }}
                {% endif %}
            </div>
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1 "></div>
        <div class="col-sm-5 col-md-5 col-lg-5 col-xs-12">
            <section name="loginArea" role="region">
                <form action="{% url 'private_api:authorize_direct_app_url' %}" class="form-horizontal iam-form" method="post" id="authForm" name="authForm" role="form">
                    <center>
                        <!--img src="{% static 'app/images/logo.png' %}" class="center img-responsive padding-top-20" alt="{{title}}" /-->
                        <h2>Sign In</h2>
                    </center>
                    <hr>
                    <fieldset>
                        <div class="form-group">
                            <div class="col-sm-2 col-md-2 col-lg-2"></div>
                            <div class="col-sm-8 col-md-8 col-lg-8 col-xs-8" id="invalid-credentials" style="font-size:small"></div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-md-2 col-sm-2 col-lg-2"></div>
                            <div class="col-sm-8 col-md-8 col-lg-8 col-xs-12">
                                <label class="control-label" style="margin-left: 40px" for="username">Username</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-md-2 col-sm-2 col-lg-2"></div>
                            <div class="col-sm-8 col-md-8 col-lg-8 col-xs-12">
                                <center><input type="text" class="form-control" name="username" id="username" autocomplete="off" maxlength="200" placeholder="username" /></center>
                            </div> 
                        </div>
                        <!--password-->
                        <div class="row">
                            <div class="col-xs-12 col-md-2 col-sm-2 col-lg-2"></div>
                            <div class="col-sm-8 col-md-8 col-lg-8 col-xs-12 center">
                                <label class="control-label" style="margin-left: 40px" for="pwd">Password</label>
                            </div>
                            <div class="col-xs-1 col-md-2 col-sm-2 col-lg-2"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12 col-md-2 col-sm-2 col-lg-2"></div>
                            <div class="col-sm-8 col-md-8 col-lg-8 col-xs-12">
                                <center><input type="password" class="form-control" name="password" id="password" autocomplete="off" maxlength="200" placeholder="password" /></center>
                            </div> 
                        </div>

                        <div class="form-group">
                            <div class="col-sm-2 col-md-2 col-lg-2 col-xs-12"></div>
                            <div class="col-md-8 col-sm-8 col-lg-8 col-xs-12">
                                <center><button type="submit" class="btn btn-primary btn-block btn-lg" id="registry-submit" role="button" style="width:280px">Sign In</button></center>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group">
                            <div class="col-sm-2 col-md-2 col-lg-2 col-xs-12"></div>
                            <div class="col-md-8 col-sm-8 col-lg-8 col-xs-12">
                                <center>
                                    <span class="text-muted center iam-info-link">
                                        Not a member? <a href="{% url 'signup_request_form' %}" class="text-primary" >Join now</a> <span class="text-muted">|</span> <a href="{% url 'signup_form' %}" class="text-primary">Forgot password</a>
                                    </span>
                                </center>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </section>
        </div>
    </div>
</div>
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="{% static 'app/scripts/iam.js' %}"></script>
<script type="text/javascript" src="{% static 'app/scripts/cookies.js' %}"></script>
<script type="text/javascript">$(document).ready(function () { IAM.authorize("{{client_id}}", "{{redirect_uri}}"); });</script>
{% endblock %}

app/templates/app/base.html
{% load analytical %}
<!DOCTYPE html>
<html lang="en">
    {% analytical_head_top %}
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="IAM">
        <meta name="keywords" content="Prosperity4All, p4all, Singular Logic SA, IAM">
        <meta name="author" content="Singular Logic SA">
        <title>{% block title%} IAM | {{ title }}{% endblock title %}</title>

         {% load staticfiles %}
        <!--link rel="shortcut icon" type="image/png" href="{{ MEDIA_URL }}app/aod/favicon/favicon.png" /-->
        <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'app/content/footer.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'app/content/sweetalert/sweetalert.css' %}" />
        <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css"/>
        {% block extraCss %}{% endblock extraCss %}
        {% analytical_head_bottom %}
    </head>

    <body class="base-body">
        {% analytical_body_top %}
        <!--<div id="preloader">
            <div id="status">&nbsp;</div>
        </div>
-->
        <div id="wrap">
            {% block navbar %}{% endblock navbar %}
            {% block content %}{% endblock content %}
        </div>
        
        <!-- Footer base -->
        {% block footer %}
        <footer id="footer">
            <div class="container body-content">
                <div style="margin-top:10px">
                    <div class="row">
                        <center>
                            <p class="center "  style="color: #fff !important">
                                <span><a href="http://www.prosperity4all.eu/" target="_blank" style="color: #fff !important">Prosperity4All</a> <span class="fa fa-copyright"></span> 2014 - {{ YEAR }}</span>
                            </p>
                        </center>
                    </div>
                    <div>
                        <div class="col-lg-2 col-sm-2 col-md-2 col-xs-4 " >
                            <img alt="European commission logo" width="100" src="{% static 'app/images/eu.png' %}"/>
                        </div>
                        <div class="col-lg-10 col-sm-10 col-md-10 col-xs-8" >
                            <span class="pull-left" style="font-size:small">
                            Prosperity4All - Ecosystem infrastructure for smart and personalised inclusion and PROSPERITY for ALL stakeholders<br> 
                            This project has received funding from the European Union’s Seventh Programme for research, technological development and demonstration under grant agreement, No 610510
                            </span>
                        </div>
                    </div>
                </div>
            </div> 
        </footer>
        {% endblock footer %}

        <!-- Scripts -->
        <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
        <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
        <script src="{% static 'app/scripts/jquery.validate.js' %}"></script>
        <script src="{% static 'app/scripts/sweetalert/sweetalert.min.js' %}"></script>
        <script type="text/javascript">
            //$(window).load(function() { // makes sure the whole site is loaded
            //    $('#status').fadeOut(); // will first fade out the loading animation
            //    $('#preloader').delay(350).fadeOut('slow'); // will fade out the white DIV that covers the website.
            //    $('body').delay(350).css({'overflow':'visible'});
            //})
            $(document).ready(function () {
                $(".nav.navbar-nav li.dropdown").mouseover(function () {
                    $(this).addClass('open');
                }).mouseleave(function () {
                    $(this).removeClass('open');
                });
            })
        </script>
        {% block scripts %}{% endblock scripts %}
        {% analytical_body_bottom %}
    </body>
</html>

app/templates/app/login.html
{% extends "app/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container body-content" id="main">
    <div class="row">
        <div class="col-sm-3 col-md-3 col-lg-3"></div>
        <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
            <section name="loginArea" role="region">
                <form action="{% url 'private_api:authenticate_url' %}" class="form-horizontal iam-login" method="post" id="loginForm" name="loginForm" role="form">
                    <center>
                        <h1>Identity & Access Manager</h1>
                    </center>
                    <hr>
                    <fieldset>
                        <div class="row">
                            <div class="col-sm-3 col-md-3 col-lg-3"></div>
                            <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12 center" id="invalid-credentials" style="font-size:small;"></div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-md-2 col-sm-2 col-lg-2"></div>
                            <div class="col-sm-8 col-md-8 col-lg-8 col-xs-12">
                                <label class="control-label" style="margin-left: 40px" for="username">Username</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-md-2 col-sm-2 col-lg-2"></div>
                            <div class="col-sm-8 col-md-8 col-lg-8 col-xs-12">
                                <center><input type="text" class="form-control" name="username" id="username" autocomplete="off" maxlength="200" placeholder="username" /></center>
                            </div> 
                        </div>
                        <!--password-->
                        <div class="row">
                            <div class="col-xs-12 col-md-2 col-sm-2 col-lg-2"></div>
                            <div class="col-sm-8 col-md-8 col-lg-8 col-xs-12 center">
                                <label class="control-label" style="margin-left: 40px" for="pwd">Password</label>
                            </div>
                            <div class="col-xs-1 col-md-2 col-sm-2 col-lg-2"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12 col-md-2 col-sm-2 col-lg-2"></div>
                            <div class="col-sm-8 col-md-8 col-lg-8 col-xs-12">
                                <center><input type="password" class="form-control" name="password" id="password" autocomplete="off" maxlength="200" placeholder="password" /></center>
                            </div> 
                        </div>

                        <div class="form-group">
                            <div class="col-sm-2 col-md-2 col-lg-2 col-xs-12"></div>
                            <div class="col-md-8 col-sm-8 col-lg-8 col-xs-12">
                                <center><button type="submit" class="btn btn-primary btn-block btn-lg" id="registry-submit" role="button" style="width:280px">Sign In</button></center>
                            </div>
                        </div>
                        <hr>
                        <div class="form-group">
                            <div class="col-sm-2 col-md-2 col-lg-2 col-xs-12"></div>
                            <div class="col-md-8 col-sm-8 col-lg-8 col-xs-12">
                                <center>
                                    <span class="center iam-info-link">
                                        Not a member? <a href="{% url 'signup_request_form' %}" class="text-primary" >Join now</a> <span class="text-muted">|</span> <a href="#" class="text-primary">Forgot password</a>
                                    </span>
                                </center>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </section>
        </div>
    </div>
</div>
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="{% static 'app/scripts/iam.js' %}"></script>
<script type="text/javascript" src="{% static 'app/scripts/cookies.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function () { 
        IAM.login("{% url 'dashboard_form' %}"); 
    });
</script>
{% endblock %}

app/templates/app/pre_registration.html
{% extends "app/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container body-content" id="main">
    <div class="row">
        <div class="col-sm-3 col-md-3 col-lg-3"></div>
        <div class="col-sm-6 col-md-6 col-lg-6 col-xs-12">
            <section name="loginArea" role="region">
                <form action="{% url 'private_api:pre_registration_url' %}" class="form-horizontal iam-form" method="post" id="preRegistrationForm" name="preRegistrationForm" role="form">
                    <center>
                        <img src="{% static 'app/images/logo.png' %}" class="center img-responsive padding-top-20" alt="{{title}}" />
                    </center>
                    <hr>
                    <fieldset>
                        <div class="row">
                            <div class="col-xs-12 col-md-2 col-sm-2 col-lg-2"></div>
                            <div class="col-sm-8 col-md-8 col-lg-8 col-xs-12">
                                <label class="control-label pull-left" for="mail">Email address</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12 col-md-2 col-sm-2 col-lg-2"></div>
                            <div class="col-sm-8 col-md-8 col-lg-8 col-xs-12">
                                <input type="text" class="form-control" name="mail" id="mail" autocomplete="off" maxlength="200" placeholder="" />
                            </div> 
                        </div>

                        <div class="form-group">
                            <div class="col-sm-2 col-md-2 col-lg-2 col-xs-12"></div>
                            <div class="col-md-8 col-sm-8 col-lg-8 col-xs-12">
                                <button type="submit" class="btn btn-primary btn-md" id="registry-submit" role="button">Submit</button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </section>
        </div>
    </div>
</div>
{% endblock %}


{% block scripts %}
<script type="text/javascript" src="{% static 'app/scripts/iam.js' %}"></script>
<script type="text/javascript" src="{% static 'app/scripts/cookies.js' %}"></script>
<script type="text/javascript">$(document).ready(function () { IAM.preRegister("{% url 'login_form'%}", "{% url 'private_api:requests_url' %}"); });</script>
{% endblock %}